<?php
/**
 * @file
 * Code for the Staff Committee feature.
 */

include_once 'staff_committee.features.inc';
/**
 * Implements hook_init().
 */
function staff_committee_init() {
  drupal_add_css(drupal_get_path('module', 'staff_committee') . '/css/staff_committee.css');
}

/**
 * Implements hook_menu().
 */
function staff_committee_menu() {
  $items['committees'] = array(
    'title' => 'Committees',
    'page callback' => '_staff_committee_page',
    'access callback' => 1,
    'menu_name' => 'navigation',
    'type' => MENU_NORMAL_ITEM,
    'hidden' => 0,
    'weight' => -2,
    'expanded' => 1,
  );

  return $items;
}

/**
 * Implements hook_theme_registry_alter().
 */
function staff_committee_theme_registry_alter(&$theme_registry) {
    // Defined path to the current module.
    $module_path = drupal_get_path('module', 'staff_committee');
    // Find all .tpl.php files in this module's folder recursively.
    $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
    // Iterate through all found template file objects.
    foreach ($template_file_objects as $key => $template_file_object) {
        // If the template has not already been overridden by a theme.
        if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
            // Alter the theme path and template elements.
            $theme_registry[$key]['theme path'] = $module_path;
            $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
            $theme_registry[$key]['type'] = 'module';
        }
    }
}

function _staff_committee_page() {
  return 'Committees menu page placeholder';
}
